/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import gui.PrincipalPanel;
import gui.dialog.SobreSistemaDialog;
import gui.cadastro.ClienteCadastroPanel;
import gui.cadastro.FilmeCadastroPanel;
import gui.cadastro.UsuarioCadastroPanel;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.JDialog;
import repository.ConnectionDatabase;
import util.ImageUtil;
import util.Views;

/**
 *
 * @author alefi
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     * 
     */
    private CardLayout cardLayout;
    
    public MainFrame() {
        initComponents();
        
        Image image = ImageUtil.loadImageFromResources("/resources/filme.png");
        setIconImage(image);
        this.setLocationRelativeTo(null);
        initUi();
        cardLayout = (CardLayout) panel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroFilme = new javax.swing.JMenuItem();
        cadastroUsuario = new javax.swing.JMenuItem();
        menuMovimentacao = new javax.swing.JMenu();
        movAlugar = new javax.swing.JMenuItem();
        movDevolver = new javax.swing.JMenuItem();
        movMostrarFilmes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAuxilio = new javax.swing.JMenu();
        sobreSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        panel.setLayout(new java.awt.CardLayout());

        menuArquivo.setText("Início");
        menuArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuArquivoMouseClicked(evt);
            }
        });
        menuBar.add(menuArquivo);

        menuCadastro.setText("Cadastro");

        cadastroCliente.setText("Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroCliente);

        cadastroFilme.setText("Filme");
        cadastroFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroFilmeActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroFilme);

        cadastroUsuario.setText("Usuário");
        cadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroUsuario);

        menuBar.add(menuCadastro);

        menuMovimentacao.setText("Ações");

        movAlugar.setText("Aluguel");
        menuMovimentacao.add(movAlugar);

        movDevolver.setText("Devolução");
        menuMovimentacao.add(movDevolver);

        movMostrarFilmes.setText("Mostrar Filmes");
        menuMovimentacao.add(movMostrarFilmes);

        jMenuItem1.setText("Alterar Senha Usuário");
        menuMovimentacao.add(jMenuItem1);

        menuBar.add(menuMovimentacao);

        menuAuxilio.setText("Auxílio");

        sobreSistema.setText("Sobre o Sistema");
        sobreSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreSistemaActionPerformed(evt);
            }
        });
        menuAuxilio.add(sobreSistema);

        menuBar.add(menuAuxilio);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreSistemaActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new SobreSistemaDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_sobreSistemaActionPerformed

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel, Views.CADASTRO_CLIENTE);
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void menuArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuArquivoMouseClicked
        // TODO add your handling code here:
        cardLayout.show(panel, Views.PAINEL_PRINCIPAL);
    }//GEN-LAST:event_menuArquivoMouseClicked

    private void cadastroFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroFilmeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel, Views.CADASTRO_FILME);
    }//GEN-LAST:event_cadastroFilmeActionPerformed

    private void cadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUsuarioActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel, Views.CADASTRO_USUARIO);
    }//GEN-LAST:event_cadastroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ConnectionDatabase.conectar();
        ConnectionDatabase.statusConexao();
        ConnectionDatabase.desconectar();
        /* Create and display the form */
        //LoginDialog loginDialog = new LoginDialog(null, true);
        //loginDialog.setVisible(true); 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private void initUi(){
        panel.add(new PrincipalPanel(),Views.PAINEL_PRINCIPAL);
        panel.add(new FilmeCadastroPanel(),Views.CADASTRO_FILME);
        panel.add(new ClienteCadastroPanel(),Views.CADASTRO_CLIENTE);
        panel.add(new UsuarioCadastroPanel(),Views.CADASTRO_USUARIO);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroFilme;
    private javax.swing.JMenuItem cadastroUsuario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuAuxilio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuMovimentacao;
    private javax.swing.JMenuItem movAlugar;
    private javax.swing.JMenuItem movDevolver;
    private javax.swing.JMenuItem movMostrarFilmes;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem sobreSistema;
    // End of variables declaration//GEN-END:variables
}
